import aiohttp
import discord
from redbot.core import commands


class InspireMe(commands.Cog):
    """Generate inspirational quote images from InspiroBot."""

    API_URL = "https://inspirobot.me/api"

    def __init__(self, bot):
        self.bot = bot
        self.session = aiohttp.ClientSession()

    def cog_unload(self):
        # Close the HTTP session when the cog is unloaded.
        self.bot.loop.create_task(self.session.close())

    @commands.command(name="inspireme", aliases=["inspire"])
    @commands.cooldown(1, 5, commands.BucketType.user)
    async def inspireme(self, ctx):
        """Generate an inspirational quote from InspiroBot."""
        async with ctx.typing():
            try:
                async with self.session.get(
                    self.API_URL, params={"generate": "true"}
                ) as resp:
                    if resp.status != 200:
                        await ctx.send(
                            f"❌ InspiroBot returned an error (HTTP {resp.status}). "
                            "Try again later."
                        )
                        return
                    image_url = (await resp.text()).strip()
            except aiohttp.ClientError as exc:
                await ctx.send(f"❌ Couldn't reach InspiroBot: {exc}")
                return

        if not image_url.startswith("http"):
            await ctx.send("❌ InspiroBot didn't return a valid image. Try again.")
            return

        embed = discord.Embed(color=await ctx.embed_color())
        embed.set_image(url=image_url)
        embed.set_footer(text="Generated by InspiroBot • inspirobot.me")
        await ctx.send(embed=embed)
